### PR TITLE
Add support for running without virtualenv.

### PR DESCRIPTION
**Pull request by adiroiban**
Scope
=====

This updated the build process so that we can run it without virtualenv. Manly to make it easy to run on Windows.

Why we got into this (5 whys)
=============================

* The migration to Read The Docs was done in a hurry

Changes
=======
Add paver.sh and pavement
Update the dev documentation.

How to try and test the changes
===============================

reviewers: @hcs0 @lgheorghiu @dumol 

Check that you can clean and run the project based on the documentation.

Thanks!

### CODE REVIEW

**Comment by hcs0** [comment]
When I switched to this branch and run `paver deps` I am getting:

```
$ ./paver.sh deps
Bootstrapping python2.7-macos1012-x64 environment to build-macos1012-x64...
No python2.7-macos1012-x64 environment. Start downloading it...
Spider mode enabled. Check if remote file exists.
--2017-12-14 14:51:44--  https://binary.chevah.com/production/python/macos1012/x64/python-2.7.14.620df8b0-macos1012-x64.tar.gz
Resolving binary.chevah.com (binary.chevah.com)... 185.92.222.246
Connecting to binary.chevah.com (binary.chevah.com)|185.92.222.246|:443... connected.
ERROR: cannot verify binary.chevah.com's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Unable to locally verify the issuer's authority.
To connect to binary.chevah.com insecurely, use `--no-check-certificate'.
The requested version was not found on the remote server.
``

**Comment by adiroiban** [comment]
> When I switched to this branch and run paver deps I am getting:

It looks like Let's encrypt CA is not accepted on your side. Maybe @dumol can help.
I don't know which list of CA is distributed by default with our Python version on OSX.

On linux and windows all looks fine.

We might want to add `--trusted-host pypi.chevah.com` to go over HTTP, but  I would like to see what is the different on OSX and maybe we can use HTTPS for geck.

needs-review

**Comment by lgheorghiu** [comment]
It's working on Windows.

**Comment by dumol** [comment]
> > When I switched to this branch and run paver deps I am getting:
> 
> It looks like Let's encrypt CA is not accepted on your side. Maybe @dumol can help.
> I don't know which list of CA is distributed by default with our Python version on OSX.

There are no certs bundled with our Python package. That error is from `wget`, not from our Python binary. 

@hcs0, check that your `wget` works with HTTPs sites and the certs it uses are not terribly out of date. Can't reproduce your issue on our MacOS build slave: 
```
chevah@bs1f-macos-1012-x64-54:~$ wget https://binary.chevah.com/production/python/macos1012/x64/python-2.7.14.620df8b0-macos1012-x64.tar.gz
--2017-12-14 17:06:51--  https://binary.chevah.com/production/python/macos1012/x64/python-2.7.14.620df8b0-macos1012-x64.tar.gz
Resolving binary.chevah.com... 185.92.222.246
Connecting to binary.chevah.com|185.92.222.246|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 32248320 (31M) [application/x-gzip]
Saving to: ‘python-2.7.14.620df8b0-macos1012-x64.tar.gz’

python-2.7.14.620df8b0-macos 100%[==============================================>]  30.75M  5.36MB/s    in 6.1s

2017-12-14 17:06:58 (5.03 MB/s) - ‘python-2.7.14.620df8b0-macos1012-x64.tar.gz’ saved [32248320/32248320]
```

**Comment by dumol** [comment]
**changes-approved**

**Pull request merged**
